INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (1, N'Ates', 1)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (2, N'Oksuruk', 1)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (3, N'Halsizlik', 2)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (4, N'Tat Kaybi', 2)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (5, N'Koku Kaybi', 2)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (6, N'Tat Kaybi', 3)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (7, N'Koku Kaybi', 3)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (8, N'Ates', 4)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (9, N'Koku Kaybi', 4)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (10, N'Ates', 5)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (11, N'Oksuruk', 5)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (12, N'Halsizlik', 5)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (13, N'Tat Kaybi', 5)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (14, N'Koku Kaybi', 5)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (15, N'Bas Agrisi', 6)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (16, N'Ates', 7)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (17, N'Koku Kaybi', 7)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (18, N'Bogaz Agrisi', 8)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (19, N'Ates', 9)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (20, N'Halsizlik', 9)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (21, N'Ates', 10)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (22, N'Tat Kaybi', 10)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (23, N'Koku Kaybi', 10)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (24, N'Halsizlik', 11)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (25, N'Ates', 11)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (26, N'Bogaz Agrisi', 12)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (27, N'Bas Agrisi', 12)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (28, N'Halsizlik', 13)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (29, N'Tat Kaybi', 13)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (30, N'Koku Kaybi', 13)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (31, N'Koku Kaybi', 14)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (32, N'Tat Kaybi', 14)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (33, N'Ates', 15)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (34, N'Koku Kaybi', 15)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (35, N'Ates', 16)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (36, N'Bogaz Agrisi', 16)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (37, N'Tat Kaybi', 17)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (38, N'Koku Kaybi', 17)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (39, N'Halsizlik', 17)
INSERT INTO [dbo].[CovidBelirtiler] ([Id], [Belirti], [CovidId]) VALUES (40, N'Ates', 18)

